# Generated by Django 4.2.2 on 2023-06-15 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinklarastis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ManyToManyField(to='tinklarastis.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_posts', to='tinklarastis.blogpost'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_posts', to='tinklarastis.blogpost')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video',
            field=models.ManyToManyField(to='tinklarastis.video'),
        ),
    ]
