# Generated by Django 4.2.2 on 2023-06-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinklarastis', '0002_blogpost_image_alter_image_post_video_blogpost_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
