# Generated by Django 4.2.2 on 2023-06-19 11:14

from django.conf import settings
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tinklarastis', '0003_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='tinklarastis.image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='video',
            field=models.ManyToManyField(blank=True, null=True, to='tinklarastis.video'),
        ),
    ]
