# Generated by Django 4.2.2 on 2023-06-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinklarastis', '0004_blogpost_featured_blogpost_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ManyToManyField(to='tinklarastis.image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='video',
            field=models.ManyToManyField(to='tinklarastis.video'),
        ),
    ]
