# Generated by Django 4.2.2 on 2023-06-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinklarastis', '0007_remove_blogpost_image_remove_blogpost_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
