# Generated by Django 4.2.2 on 2023-06-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinklarastis', '0009_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='post',
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
