# Generated by Django 4.2.2 on 2023-06-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinklarastis', '0010_rename_video_video_file_remove_video_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='video',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='videos',
            field=models.ManyToManyField(blank=True, to='tinklarastis.video'),
        ),
    ]
