# Generated by Django 4.2.2 on 2023-06-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinklarastis', '0012_remove_blogpost_image_alter_blogpost_videos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='file',
            new_name='video',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ManyToManyField(blank=True, to='tinklarastis.image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='videos',
            field=models.ManyToManyField(blank=True, to='tinklarastis.video'),
        ),
    ]
